/* Shared authentication, dedicated login and profile pages. */
(() => {
 'use strict';
 const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const copy={
 en:{login:'Log in',logout:'Log out',profile:'My profile',register:'Student registration',club:'Register a club',welcome:'Your campus, connected.',intro:'One account for campus conversations and your club community.',email:'Email',password:'Password',username:'Username',usernameHint:'Your public display name (2–30 characters). Sign in with your email.',factor:'Authenticator / recovery code (if enabled)',clubName:'Club name',contact:'Person in charge',description:'Tell us about your club',submitClub:'Submit for approval',pending:'Application submitted. An administrator must approve it before an account is created. After approval, log in with the email and password you provided. Contact the site administrator for the result; no email is sent automatically.',clubHint:'Club accounts require administrator approval. They can post in the forum but do not have administrator access.',registerHint:'Password: 10–72 characters, no more than 72 UTF-8 bytes.',save:'Save changes',saved:'Profile updated.',avatar:'Change avatar',photoHint:'JPG, PNG or WebP; up to 4 MB and 6 megapixels. Your avatar is public on non-anonymous posts.',myPosts:'My forum posts',empty:'You have not posted yet.',more:'Load more',anonymous:'Anonymous post',hidden:'Hidden by moderation',open:'Open post',newPost:'Go to forum',loading:'Loading…',error:'Unable to connect. Please try again.',needLogin:'Log in to view your profile.',student:'Student',clubAccount:'Club',account:'Account',show:'Show password',hide:'Hide password',loggedOut:'You are logged out.',approved:'Approved',rejected:'Rejected',review:'Club applications',pendingLabel:'Pending review',approve:'Approve & create account',reject:'Reject',note:'Review note (required for rejection)',noApplications:'No applications in this category.',next:'Next',prev:'Previous',reviewed:'Application reviewed.',confirmApprove:'Approve this club and create its account?',confirmReject:'Reject this club application?',admin:'Admin dashboard',session:'Your session expired. Please log in again.'},
 ms:{login:'Log masuk',logout:'Log keluar',profile:'Profil saya',register:'Daftar pelajar',club:'Daftar kelab',welcome:'Kampus anda, komuniti kita.',intro:'Satu akaun untuk perbualan kampus dan komuniti kelab anda.',email:'E-mel',password:'Kata laluan',username:'Nama pengguna',usernameHint:'Nama paparan awam (2–30 aksara). Log masuk menggunakan e-mel.',factor:'Kod pengesah / pemulihan (jika diaktifkan)',clubName:'Nama kelab',contact:'Pegawai yang bertanggungjawab',description:'Ceritakan tentang kelab anda',submitClub:'Hantar untuk kelulusan',pending:'Permohonan dihantar. Pentadbir perlu meluluskan permohonan sebelum akaun diwujudkan. Selepas diluluskan, log masuk dengan e-mel dan kata laluan yang diberikan. Hubungi pentadbir laman untuk keputusan; tiada e-mel dihantar secara automatik.',clubHint:'Akaun kelab memerlukan kelulusan pentadbir. Akaun ini boleh menulis dalam forum tetapi tidak mempunyai akses pentadbir.',registerHint:'Kata laluan: 10–72 aksara, maksimum 72 bait UTF-8.',save:'Simpan perubahan',saved:'Profil dikemas kini.',avatar:'Tukar gambar profil',photoHint:'JPG, PNG atau WebP; maksimum 4 MB dan 6 megapiksel. Gambar dipaparkan pada siaran bukan tanpa nama.',myPosts:'Siaran forum saya',empty:'Anda belum menulis sebarang siaran.',more:'Muat lagi',anonymous:'Siaran tanpa nama',hidden:'Disembunyikan oleh moderator',open:'Buka siaran',newPost:'Ke forum',loading:'Memuatkan…',error:'Tidak dapat menyambung. Cuba lagi.',needLogin:'Log masuk untuk melihat profil anda.',student:'Pelajar',clubAccount:'Kelab',account:'Akaun',show:'Tunjuk kata laluan',hide:'Sembunyikan kata laluan',loggedOut:'Anda telah log keluar.',approved:'Diluluskan',rejected:'Ditolak',review:'Permohonan kelab',pendingLabel:'Menunggu kelulusan',approve:'Lulus & cipta akaun',reject:'Tolak',note:'Catatan semakan (wajib untuk penolakan)',noApplications:'Tiada permohonan dalam kategori ini.',next:'Seterusnya',prev:'Sebelumnya',reviewed:'Permohonan telah disemak.',confirmApprove:'Luluskan kelab ini dan cipta akaunnya?',confirmReject:'Tolak permohonan kelab ini?',admin:'Panel pentadbir',session:'Sesi anda tamat. Sila log masuk semula.'},
 zh:{login:'登录',logout:'退出登录',profile:'个人资料',register:'学生注册',club:'注册社团',welcome:'校园生活，从这里连接。',intro:'使用一个账号参与校园讨论，建立你的社团社区。',email:'电邮',password:'密码',username:'用户名',usernameHint:'公开显示名称（2–30 字），登录仍使用电邮。',factor:'验证器／恢复码（已启用时填写）',clubName:'社团名称',contact:'负责人姓名',description:'介绍你的社团',submitClub:'提交审批',pending:'申请已提交。管理员批准后才会创建账号，之后可使用所填电邮及密码登录。请联系网站管理员查询结果，系统不会自动发送电邮。',clubHint:'社团账号必须由管理员审批，可使用论坛，但不会获得管理权限。',registerHint:'密码 10–72 字符，UTF-8 不超过 72 字节。',save:'保存修改',saved:'个人资料已更新。',avatar:'更换头像',photoHint:'JPG、PNG 或 WebP，最大 4 MB、600 万像素。非匿名帖会公开显示头像。',myPosts:'我的论坛帖子',empty:'你还没有发过帖子。',more:'加载更多',anonymous:'匿名帖子',hidden:'已被管理隐藏',open:'打开帖子',newPost:'前往论坛',loading:'加载中…',error:'暂时无法连接，请重试。',needLogin:'请先登录以查看个人资料。',student:'学生',clubAccount:'社团',account:'账号',show:'显示密码',hide:'隐藏密码',loggedOut:'已退出登录。',approved:'已批准',rejected:'已拒绝',review:'社团申请',pendingLabel:'待审批',approve:'批准并创建账号',reject:'拒绝',note:'审核备注（拒绝时必填）',noApplications:'此分类暂无申请。',next:'下一页',prev:'上一页',reviewed:'申请已处理。',confirmApprove:'批准此社团申请并创建账号？',confirmReject:'拒绝此社团申请？',admin:'管理后台',session:'登录已过期，请重新登录。'}
 };
 let user=null,mode='login',postPage=1;
 const lang=()=>window.PMS_UI?.language||'en', t=k=>(copy[lang()]||copy.en)[k]||k;
 Object.assign(copy.en,{checkStatus:'Check application status',pendingLabel:'Pending review',statusHint:'Use the application email and password to check the result. If rejected, update the form and submit again.'});
 Object.assign(copy.ms,{checkStatus:'Semak status permohonan',statusHint:'Gunakan e-mel dan kata laluan permohonan untuk menyemak keputusan. Jika ditolak, kemas kini borang dan hantar semula.'});
 Object.assign(copy.zh,{checkStatus:'查询申请状态',statusHint:'用申请时填写的电邮和密码查询结果。如被拒绝，可修改表单后重新提交。'});
 const token=()=>sessionStorage.getItem('pms-forum-token')||'';
 function url(action,params={}){const u=new URL(window.PMS_FORUM_CONFIG.api);u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));return u.href;}
 async function api(action,data,params={}){
  const h={'Accept-Language':lang()};if(token())h.Authorization='Bearer '+token();if(data!==undefined&&!(data instanceof FormData))h['Content-Type']='application/json';
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
  try{const r=await fetch(url(action,params),{method:data===undefined?'GET':'POST',headers:h,body:data===undefined?undefined:data instanceof FormData?data:JSON.stringify(data),credentials:'omit',cache:'no-store',signal:controller.signal});const j=await r.json();if(!r.ok||!j.ok){if(r.status===401&&action!=='login'){sessionStorage.removeItem('pms-forum-token');user=null;renderAccount();}throw Error(j.error||t('error'));}return j;}catch(e){throw Error(e.name==='AbortError'||e.name==='SyntaxError'||e instanceof TypeError?t('error'):e.message);}finally{clearTimeout(timer);}
 }
 const destination=()=>{const v=new URL(location.href).searchParams.get('next');return ['index.html','community.html','campus.html','admin.html','profile.html'].includes(v)?v:'profile.html';};
 function loginLink(){const name=location.pathname.split('/').pop();return 'login.html?next='+encodeURIComponent(['index.html','community.html','campus.html','admin.html','profile.html'].includes(name)?name:'profile.html');}
 async function logout(){const b=$('#shared-auth');if(b)b.disabled=true;try{await api('logout',{});}catch(e){if(token()){alert(e.message);if(b)b.disabled=false;return;}}sessionStorage.removeItem('pms-forum-token');location.assign('login.html');}
 function renderAccount(){
  const controls=$('#shared-account');if(controls)controls.innerHTML=(user?`<a class="profile-link" href="profile.html">${esc(t('profile'))}</a>`:'')+`<button type="button" id="shared-auth">${esc(t(user?'logout':'login'))}</button>`;
  const auth=$('#shared-auth');if(auth)auth.onclick=()=>user?logout():location.assign(loginLink());
  const link=$('#pms-menu-account');if(link){link.textContent=t(user?'logout':'login');link.href=user?'#logout':loginLink();link.onclick=e=>{if(user){e.preventDefault();logout();}};}
  const profile=$('#pms-menu-profile');if(profile){profile.textContent=t('profile');profile.hidden=!user;}
  const admin=$('#pms-menu-admin');if(admin)admin.hidden=user?.role!=='admin';
 }
 function header(){
  const h=$('body>header');if(!h)return;
  h.classList.add('account-header');
  let toolbar=h.querySelector('.compact-toolbar');if(!toolbar){toolbar=document.createElement('div');toolbar.className='compact-toolbar';h.append(toolbar);const a=h.querySelector('.pms-navigation-actions');if(a)toolbar.append(a);}
  const controls=document.createElement('div');controls.id='shared-account';controls.setAttribute('data-no-translate','');toolbar.prepend(controls);
  const logo=h.querySelector('.logo');if(logo){logo.setAttribute('data-no-translate','');logo.innerHTML='<span class="logo-word">PMS</span><small>EXPLORE</small>';}
  let search=h.querySelector('.global-search-button');
  if(!search){search=document.createElement('button');search.type='button';search.className='global-search-button';search.setAttribute('data-no-translate','');search.textContent=({en:'Search this site',ms:'Cari dalam laman',zh:'全站搜索'})[lang()]||'Search this site';search.onclick=()=>location.assign('index.html?search=1');document.addEventListener('pms-language-change',()=>{search.textContent=({en:'Search this site',ms:'Cari dalam laman',zh:'全站搜索'})[lang()]||'Search this site';});}
  toolbar.prepend(search);
  if(location.pathname.endsWith('index.html')&&new URL(location.href).searchParams.get('search')==='1')search.click();
  renderAccount();
 }
 function translate(){document.querySelectorAll('[data-ac]').forEach(e=>e.textContent=t(e.dataset.ac));const select=$('#account-language');if(select)select.value=lang();renderAccount();if($('#auth-page'))setMode(mode);}
 function setMode(value){mode=value;document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('selected',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));});document.querySelectorAll('[data-for]').forEach(el=>{el.hidden=!el.dataset.for.split(' ').includes(mode);el.querySelectorAll('input,textarea').forEach(i=>{i.disabled=el.hidden;i.required=!el.hidden&&i.name!=='otp';});});const pw=$('#auth-page [name=password]');if(pw)pw.autocomplete=mode==='login'?'current-password':'new-password';const button=$('#auth-submit');if(button)button.textContent=t(mode==='club'?'submitClub':mode==='register'?'register':'login');}
 async function busy(form,fn){const button=form.querySelector('[type=submit]');button.disabled=true;try{await fn();}finally{button.disabled=false;}}
 function initLogin(){
  if(!$('#auth-page'))return;
  const statusButton=document.createElement('button');statusButton.type='button';statusButton.className='secondary';statusButton.dataset.for='club';statusButton.dataset.ac='checkStatus';
  const hint=document.createElement('p');hint.dataset.for='club';hint.dataset.ac='statusHint';$('#access-form').append(hint,statusButton);
  statusButton.onclick=async()=>{const form=$('#access-form'),notice=$('#account-notice');if(!form.elements.email.reportValidity()||!form.elements.password.reportValidity())return;statusButton.disabled=true;notice.textContent=t('loading');try{const r=await api('club_status',{email:form.elements.email.value,password:form.elements.password.value});notice.textContent=t(r.status==='pending'?'pendingLabel':r.status)+' '+(r.review_note||'');}catch(e){notice.textContent=e.message;}finally{statusButton.disabled=false;}};
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{setMode(b.dataset.mode);$('#account-notice').textContent='';});
  $('#show-password').onclick=()=>{const i=$('#auth-page [name=password]');i.type=i.type==='password'?'text':'password';$('#show-password').textContent=t(i.type==='password'?'show':'hide');};
  $('#access-form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;busy(form,async()=>{const notice=$('#account-notice');notice.textContent=t('loading');try{const d=Object.fromEntries(new FormData(form));if(new TextEncoder().encode(d.password).length>72)throw Error(t('registerHint'));const submittedMode=mode;const r=await api(submittedMode==='club'?'club_apply':submittedMode,d);if(submittedMode==='club'){form.reset();notice.textContent=t('pending');return;}sessionStorage.setItem('pms-forum-token',r.token);location.assign(destination());}catch(err){notice.textContent=err.message;}});};
 }
 function showProfile(u){user=u;$('#profile-name').textContent=u.nickname;$('#profile-email').textContent=u.email;$('#profile-kind').textContent=t(u.account_type==='club'?'clubAccount':'student');$('#profile-form [name=nickname]').value=u.nickname;const box=$('#profile-avatar');box.replaceChildren();if(u.has_avatar){const img=document.createElement('img');img.alt='';img.src=url('avatar',{id:u.id,v:Date.now()});box.append(img);}else box.textContent=[...u.nickname][0]||'P';renderAccount();}
 async function posts(append=false){const r=await api('my_posts',undefined,{page:append?postPage+1:1});postPage=append?postPage+1:1;const list=$('#my-posts');if(!append)list.replaceChildren();r.posts.forEach(p=>{const el=document.createElement('article');el.className='profile-post';el.innerHTML=`<div class="profile-post-meta">${esc(new Date(p.created_at.replace(' ','T')+'Z').toLocaleDateString(({en:'en-MY',ms:'ms-MY',zh:'zh-CN'})[lang()]))}${p.is_anonymous?` · ${esc(t('anonymous'))}`:''}${p.status==='hidden'?` · ${esc(t('hidden'))}`:''}</div><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p>${p.status==='published'?`<a href="community.html?post=${Number(p.id)}">${esc(t('open'))} →</a>`:''}`;list.append(el);});if(!list.children.length)list.textContent=t('empty');$('#posts-more').hidden=!r.has_more;}
 async function initProfile(){
  if(!$('#profile-page'))return;
  if(!token()){location.replace(loginLink());return;}
  try{showProfile((await api('profile')).user);$('#profile-content').hidden=false;await posts();}catch(e){$('#account-notice').textContent=e.message;}
  $('#profile-form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;busy(form,async()=>{try{showProfile((await api('update_profile',Object.fromEntries(new FormData(form)))).user);$('#account-notice').textContent=t('saved');}catch(err){$('#account-notice').textContent=err.message;}});};
  $('#avatar-form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;busy(form,async()=>{try{const f=form.elements.avatar.files[0];if(!f||f.size>4*1024*1024)throw Error(t('photoHint'));showProfile((await api('upload_avatar',new FormData(form))).user);form.reset();$('#account-notice').textContent=t('saved');}catch(err){$('#account-notice').textContent=err.message;}});};
  $('#posts-more').onclick=async e=>{e.target.disabled=true;try{await posts(true);}catch(err){$('#account-notice').textContent=err.message;}finally{e.target.disabled=false;}};
 }
 window.PMS_ACCOUNT={api,t,esc};
 header();translate();initLogin();initProfile();
 if(token())api('me').then(r=>{user=r.user;renderAccount();}).catch(()=>{});
 $('#account-language')?.addEventListener('change',e=>window.PMS_UI.setLanguage(e.target.value));
 document.addEventListener('pms-language-change',()=>{translate();if($('#profile-page')&&user){$('#profile-kind').textContent=t(user.account_type==='club'?'clubAccount':'student');posts().catch(()=>{});}});
 // Capture legacy account controls so every entry uses the dedicated pages.
 document.addEventListener('click',e=>{const b=e.target.closest('#account-button, #logout, [data-action=logout]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.id==='logout'||b.dataset.action==='logout')logout();else location.assign(user?'profile.html':loginLink());},true);
})();
