(() => {
 'use strict';
 const A=window.PMS_ACCOUNT,admin=window.PMS_ADMIN;if(!A||!admin)return;
 let filter='pending',page=1,request=0;
 const $=s=>document.querySelector(s),t=A.t,esc=A.esc;
 const tab=document.createElement('button');tab.dataset.tab='clubs';tab.setAttribute('data-no-translate','');$('#tabs').append(tab);
 const panel=document.createElement('section');panel.id='clubs';panel.className='panel';panel.hidden=true;panel.setAttribute('data-no-translate','');$('.content').append(panel);
 const shortcut=document.createElement('button');shortcut.type='button';shortcut.className='secondary';shortcut.setAttribute('data-no-translate','');$('#dashboard .actions').append(shortcut);shortcut.onclick=()=>tab.click();
 function ui(){tab.textContent=t('review');shortcut.textContent=t('review');panel.innerHTML=`<div class="club-filters">${['pending','approved','rejected'].map(k=>`<button data-status="${k}" class="${filter===k?'selected':''}">${esc(t(k==='pending'?'pendingLabel':k))}</button>`).join('')}</div><p id="clubs-notice" role="status" aria-live="polite"></p><div id="club-list"></div><div class="club-pages"><button id="clubs-prev" class="secondary">${esc(t('prev'))}</button><button id="clubs-next" class="secondary">${esc(t('next'))}</button></div>`;panel.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{filter=b.dataset.status;page=1;ui();load();});$('#clubs-prev').onclick=()=>{page--;load();};$('#clubs-next').onclick=()=>{page++;load();};}
 async function load(){const n=++request;$('#clubs-notice').textContent=t('loading');$('#clubs-prev').disabled=true;$('#clubs-next').disabled=true;try{const r=await A.api('admin_clubs',undefined,{status:filter,page});if(n!==request)return;$('#clubs-notice').textContent='';$('#club-list').innerHTML=r.applications.length?r.applications.map(x=>`<article class="club-request"><h2>${esc(x.club_name)}</h2><p class="club-details">${esc(x.email)} · ${esc(x.nickname)}<br>${esc(t('contact'))}: ${esc(x.contact_name)}</p><p>${esc(x.description)}</p>${filter==='pending'?`<label>${esc(t('note'))}<textarea data-note="${Number(x.id)}" rows="2" maxlength="500"></textarea></label><div class="actions"><button data-id="${Number(x.id)}" data-review="approved">${esc(t('approve'))}</button><button class="secondary" data-id="${Number(x.id)}" data-review="rejected">${esc(t('reject'))}</button></div>`:`<p class="account-info">${esc(t(filter))}${x.review_note?' · '+esc(x.review_note):''}</p>`}</article>`).join(''):`<p class="account-card">${esc(t('noApplications'))}</p>`;$('#clubs-prev').disabled=page<=1;$('#clubs-next').disabled=!r.has_more;}catch(e){if(n===request)$('#clubs-notice').textContent=e.message;}}
 panel.addEventListener('click',async e=>{const b=e.target.closest('[data-review]');if(!b)return;const decision=b.dataset.review,id=Number(b.dataset.id),note=panel.querySelector(`[data-note="${id}"]`).value.trim();if(decision==='rejected'&&!note){$('#clubs-notice').textContent=t('note');return;}if(!confirm(t(decision==='approved'?'confirmApprove':'confirmReject')))return;const buttons=b.closest('.actions').querySelectorAll('button');buttons.forEach(x=>x.disabled=true);try{await A.api('admin_review_club',{id,decision,note});await load();$('#clubs-notice').textContent=t('reviewed');}catch(err){$('#clubs-notice').textContent=err.message;buttons.forEach(x=>x.disabled=false);}});
 tab.addEventListener('click',()=>{ui();load();});$('#refresh').addEventListener('click',()=>{if(!panel.hidden)load();});document.addEventListener('pms-language-change',()=>{ui();if(!panel.hidden){$('#section-title').textContent=t('review');load();}});ui();
})();
